<?
$PERM["search"]["8"]="W";
$PERM["products"]["8"]="W";
$PERM["services"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["news"]["9"]="W";
$PERM["contacts"]["8"]="W";
$PERM["company"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["index.php"]["9"]="W";
$PERM["forum"]["8"]="W";
$PERM["forum"]["9"]="W";
$PERM["blogs"]["8"]="W";
$PERM["blogs"]["9"]="W";
?>